services:
  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    ports:
      - "5431:5432"
  backend:
    links:
      - "db:database"
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    ports:
      - "8080:8080"
  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    ports:
      - "4200:4200"
